"""Render a :class:`~pdf2tex.models.Document` to a LaTeX string."""

from __future__ import annotations

import logging
import textwrap

from . import __version__
from .charmap import escape_text
from .models import (
    Bold,
    Document,
    DisplayMath,
    Heading,
    InlineMath,
    Italic,
    ListBlock,
    Paragraph,
    Table,
    Text,
    TodoPlaceholder,
)

log = logging.getLogger(__name__)

WRAP_WIDTH = 90

_DEFAULT_PACKAGES = [
    "\\usepackage[utf8]{inputenc}",
    "\\usepackage[T1]{fontenc}",
    "\\usepackage[%(lang)s]{babel}",
    "\\usepackage{geometry}",
    "\\usepackage{amsmath}",
    "\\usepackage{amssymb}",
    "\\usepackage{booktabs}",
    "\\usepackage{multirow}",
    "\\usepackage{makecell}",
    "\\usepackage{enumitem}",
    "\\usepackage{todonotes}",
    "\\usepackage{graphicx}",
]

# Placeholder marker for custom preamble templates.
BODY_MARKER = "%%BODY%%"


def default_preamble(lang: str = "english") -> str:
    lines = ["\\documentclass[11pt,a4paper]{article}"]
    lines += [pkg % {"lang": lang} for pkg in _DEFAULT_PACKAGES]
    return "\n".join(lines)


def _header_comment(doc: Document) -> str:
    return (
        f"% Generated by pdf2tex {__version__}\n"
        f"% Source: {doc.meta.source}\n"
        f"% Date:   {doc.meta.date}\n"
    )


def _wrap(text: str) -> str:
    if not text:
        return ""
    return textwrap.fill(
        text,
        width=WRAP_WIDTH,
        break_long_words=False,
        break_on_hyphens=False,
    )


def _render_inline(inline) -> str:
    if isinstance(inline, Text):
        return escape_text(inline.text)
    if isinstance(inline, Bold):
        return "\\textbf{" + escape_text(inline.text) + "}"
    if isinstance(inline, Italic):
        return "\\textit{" + escape_text(inline.text) + "}"
    if isinstance(inline, InlineMath):
        return "$" + inline.latex + "$"
    return escape_text(str(inline))


_SECTION_CMDS = ["section", "subsection", "subsubsection", "paragraph"]


def _render_element(element) -> str:
    if isinstance(element, Paragraph):
        return _wrap("".join(_render_inline(i) for i in element.inlines))
    if isinstance(element, Heading):
        cmd = _SECTION_CMDS[min(element.level, len(_SECTION_CMDS)) - 1]
        star = "*" if element.starred else ""
        return f"\\{cmd}{star}{{{escape_text(element.text)}}}"
    if isinstance(element, DisplayMath):
        if element.number is not None or element.label:
            label = f"\\label{{{element.label}}}" if element.label else ""
            return f"\\begin{{equation}}{label}\n{element.latex}\n\\end{{equation}}"
        return f"\\[\n{element.latex}\n\\]"
    if isinstance(element, TodoPlaceholder):
        return f"\\todo[inline]{{{escape_text(element.reason)}}}"
    if isinstance(element, ListBlock):
        return _render_list(element)
    if isinstance(element, Table):
        # Rendered in a later phase; emit nothing for now.
        return ""
    return ""


def _render_list(lb: ListBlock, depth: int = 0) -> str:
    pad = "  " * depth
    out = [f"{pad}\\begin{{{lb.kind}}}"]
    for item in lb.items:
        if isinstance(item, ListBlock):
            out.append(_render_list(item, depth + 1))
        else:  # list of inline runs
            text = "".join(_render_inline(i) for i in item)
            wrapped = textwrap.fill(
                text,
                width=WRAP_WIDTH,
                initial_indent=f"{pad}  \\item ",
                subsequent_indent=f"{pad}    ",
                break_long_words=False,
                break_on_hyphens=False,
            )
            out.append(wrapped if text else f"{pad}  \\item")
    out.append(f"{pad}\\end{{{lb.kind}}}")
    return "\n".join(out)


def render(doc: Document, no_title: bool = False, preamble: str | None = None) -> str:
    body_parts: list[str] = []

    if not no_title and doc.meta.title:
        body_parts.append(f"\\title{{{escape_text(doc.meta.title)}}}")
        body_parts.append("\\author{}")
        body_parts.append("\\date{}")
        body_parts.append("\\maketitle")

    for element in doc.elements:
        rendered = _render_element(element)
        if rendered:
            body_parts.append(rendered)

    body = "\n\n".join(body_parts)

    if preamble is not None:
        if BODY_MARKER in preamble:
            return preamble.replace(BODY_MARKER, body)
        # No marker: treat the template as a preamble and wrap document body.
        head = preamble
    else:
        head = default_preamble(doc.meta.lang)

    return (
        _header_comment(doc)
        + head
        + "\n\n\\begin{document}\n\n"
        + body
        + "\n\n\\end{document}\n"
    )
